// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEhv8Ydgg9UitAwPLWp0rx_dXwvGIum0c',
    appId: '1:323912721336:web:25eaf8c19a7c2cacc9654d',
    messagingSenderId: '323912721336',
    projectId: 'chat-app-addce',
    authDomain: 'chat-app-addce.firebaseapp.com',
    storageBucket: 'chat-app-addce.firebasestorage.app',
    measurementId: 'G-JX9EGVB0GP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-X1HokxKbm-d53x6lHwKhiXMrThwufyY',
    appId: '1:323912721336:android:ea850e7942b1fbefc9654d',
    messagingSenderId: '323912721336',
    projectId: 'chat-app-addce',
    storageBucket: 'chat-app-addce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmTyEffTBch3Wi2Kwod9tERJ1Oe2aNE0E',
    appId: '1:323912721336:ios:d6dc935bd17a42ebc9654d',
    messagingSenderId: '323912721336',
    projectId: 'chat-app-addce',
    storageBucket: 'chat-app-addce.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmTyEffTBch3Wi2Kwod9tERJ1Oe2aNE0E',
    appId: '1:323912721336:ios:d6dc935bd17a42ebc9654d',
    messagingSenderId: '323912721336',
    projectId: 'chat-app-addce',
    storageBucket: 'chat-app-addce.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEhv8Ydgg9UitAwPLWp0rx_dXwvGIum0c',
    appId: '1:323912721336:web:fc9d57b1f6c34f2dc9654d',
    messagingSenderId: '323912721336',
    projectId: 'chat-app-addce',
    authDomain: 'chat-app-addce.firebaseapp.com',
    storageBucket: 'chat-app-addce.firebasestorage.app',
    measurementId: 'G-TKFEXEM4NW',
  );
}
